//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmler
    {
        public int FilmID { get; set; }
        public string FilmAdi { get; set; }
        public Nullable<int> FilmTurID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> VizyonTarihi { get; set; }
        public Nullable<int> YapimYili { get; set; }
        public Nullable<int> YonetmenID { get; set; }
        public Nullable<int> FilmDilID { get; set; }
        public Nullable<int> FilmUlkeID { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
