//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmler()
        {
            this.Cast = new HashSet<Cast>();
        }
    
        public int FilmID { get; set; }
        public string FilmAdi { get; set; }
        public Nullable<int> FilmTurID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> VizyonTarihi { get; set; }
        public Nullable<int> YapimYili { get; set; }
        public Nullable<int> YonetmenID { get; set; }
        public Nullable<int> DilID { get; set; }
        public Nullable<int> UlkeID { get; set; }
        public string Picture { get; set; }
        public string Link { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cast> Cast { get; set; }
        public virtual Dil Dil { get; set; }
        public virtual Tur Tur { get; set; }
        public virtual Ulke Ulke { get; set; }
        public virtual Yonetmen Yonetmen { get; set; }
    }
}
