//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oyuncular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oyuncular()
        {
            this.Cast = new HashSet<Cast>();
        }
    
        public int OyuncuID { get; set; }
        public Nullable<int> UlkeID { get; set; }
        public string CinsiyetID { get; set; }
        public string OyuncuAdiSoyadi { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cast> Cast { get; set; }
        public virtual Cinsiyet Cinsiyet { get; set; }
        public virtual Ulke Ulke { get; set; }
    }
}
