//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinUI.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filmler", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    [System.SerializableAttribute()]
    public partial class Filmler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilmAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilmIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilmResmiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VizyonTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YapimYiliField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama {
            get {
                return this.AciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.AciklamaField, value) != true)) {
                    this.AciklamaField = value;
                    this.RaisePropertyChanged("Aciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilmAdi {
            get {
                return this.FilmAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmAdiField, value) != true)) {
                    this.FilmAdiField = value;
                    this.RaisePropertyChanged("FilmAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilmID {
            get {
                return this.FilmIDField;
            }
            set {
                if ((this.FilmIDField.Equals(value) != true)) {
                    this.FilmIDField = value;
                    this.RaisePropertyChanged("FilmID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilmResmi {
            get {
                return this.FilmResmiField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmResmiField, value) != true)) {
                    this.FilmResmiField = value;
                    this.RaisePropertyChanged("FilmResmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> VizyonTarihi {
            get {
                return this.VizyonTarihiField;
            }
            set {
                if ((this.VizyonTarihiField.Equals(value) != true)) {
                    this.VizyonTarihiField = value;
                    this.RaisePropertyChanged("VizyonTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YapimYili {
            get {
                return this.YapimYiliField;
            }
            set {
                if ((this.YapimYiliField.Equals(value) != true)) {
                    this.YapimYiliField = value;
                    this.RaisePropertyChanged("YapimYili");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FilmleriGetir", ReplyAction="http://tempuri.org/IService1/FilmleriGetirResponse")]
        WinUI.ServiceReference1.Filmler[] FilmleriGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FilmleriGetir", ReplyAction="http://tempuri.org/IService1/FilmleriGetirResponse")]
        System.Threading.Tasks.Task<WinUI.ServiceReference1.Filmler[]> FilmleriGetirAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WinUI.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WinUI.ServiceReference1.IService1>, WinUI.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinUI.ServiceReference1.Filmler[] FilmleriGetir() {
            return base.Channel.FilmleriGetir();
        }
        
        public System.Threading.Tasks.Task<WinUI.ServiceReference1.Filmler[]> FilmleriGetirAsync() {
            return base.Channel.FilmleriGetirAsync();
        }
    }
}
